Create Burwood InfoCouncil Scraper
yimbymelbourne/council-meeting-agenda-scraper pull request #62
Opened 2024-02-14 18:39 UTC by benfrstr

Add a scraper for Burwood council.

2024-02-22 10:14 UTC, ArchangelEkim requested changes

2024-02-22 10:14 UTC, ArchangelEkim commented on scrapers/nsw/burwood.py
> +    sys.path.append(parent_dir)
These lines are unneeded with the recent restructuring of the program.

2024-02-22 10:14 UTC, ArchangelEkim commented on scrapers/nsw/burwood.py
> +from infocouncil_scraper import InfoCouncilScraper
Update imports.

```{suggestion}
from council_scrapers.base import InfoCouncilScraper, register_scraper
```

2024-02-22 18:56 UTC, benfrstr reviewed
Thanks for the requested changes!

2024-02-23 04:29 UTC, ArchangelEkim requested changes

2024-02-23 04:29 UTC, ArchangelEkim commented on scrapers/nsw/burwood.py
> +from infocouncil_scraper import InfoCouncilScraper
These changes need to be committed into the repo before I can approve

2024-02-23 13:44 UTC, benfrstr commented
It's not letting me commit the changes, only submit feedback weirdly.

2024-02-24 01:13 UTC, ArchangelEkim commented
I'll fix it from my end.

2024-02-24 01:18 UTC, ArchangelEkim approved these changes

2024-02-24 01:19 UTC, merged

2024-02-27 13:41 UTC, benfrstr commented
Thank you!