create NSW campbelltown scraper
yimbymelbourne/council-meeting-agenda-scraper pull request #75
Opened 2024-02-22 05:06 UTC by N-2-O

resolves #51

2024-02-22 06:16 UTC, N-2-O commented
> [Council Meetings](https://www.campbelltown.nsw.gov.au/Whats-On/Council-meetings) are held on the second Tuesday of the month at 6:30pm

Updated time and year

2024-02-22 09:44 UTC, ArchangelEkim requested changes
Hi Nathan, I noticed your code still uses some old imported; I'd advise ensuring you have pulled all the latest commits and reviewed the imports. 

Especially since the regexes can be imported too.

2024-02-26 11:30 UTC, chrisobi02 commented on council_scrapers/scrapers/nsw/campbelltown.py
> +
leftover code from old file structure

2024-02-26 11:31 UTC, chrisobi02 commented on council_scrapers/scrapers/nsw/campbelltown.py
> +from _dataclasses import ScraperReturn
old code - dictConfig is unused and the base_scraper should be an absolute import (similarly _dataclasses should be removed)

2024-02-26 11:33 UTC, chrisobi02 commented on council_scrapers/scrapers/nsw/campbelltown.py
> +        pattern = r"([a-zA-Z\s]+)(\d{1,2}\s+(January|February|March|April|May|June|July|August|September|October|November|December))"
compare to regex in constants.py

2024-02-29 03:41 UTC, ArchangelEkim approved these changes
It is updated to remove unnecessary code.

2024-02-29 03:41 UTC, merged